# Generated by Django 5.0.4 on 2024-05-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardingHouseApp', '0003_alter_postcomment_reply_alter_roomcomment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
    ]
