# Generated by Django 5.0.2 on 2024-05-18 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardingHouseApp', '0006_alter_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='be_Followed',
            new_name='be_followed',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
    ]
