# Generated by Django 5.0.2 on 2024-05-18 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardingHouseApp', '0007_rename_be_followed_follow_be_followed_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'be_followed')},
        ),
    ]
