# Generated by Django 5.0.2 on 2024-05-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardingHouseApp', '0008_alter_follow_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='follow',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
