# Generated by Django 5.0.2 on 2024-05-26 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardingHouseApp', '0010_remove_post_street_remove_room_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='boardingHouseApp.district'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='boardingHouseApp.district'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
