# Generated by Django 5.0.2 on 2024-05-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardingHouseApp', '0011_alter_post_district_alter_post_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='num_of_people',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
